#!/bin/sh
# Xcode Cloud runs this after cloning and before it opens the project.
# meteocool.xcodeproj is generated by XcodeGen and gitignored, so it has to be
# created here. See "Xcode Cloud" in CLAUDE.md.
set -eu
cd "$CI_PRIMARY_REPOSITORY_PATH"

brew install xcodegen
xcodegen generate

# Xcode Cloud disables automatic package resolution, so the pins must be in
# place before it resolves packages (same as restore_package_pins in
# scripts/_common.sh).
mkdir -p meteocool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
cp Package.resolved meteocool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/
