//
//  LicenceViewController.swift
//  meteocool
//
//  Open-source licences at the bottom of Settings.
//

import UIKit

/// One piece of third-party software and the notice its licence asks to
/// reproduce. `Licences.json` lists them, generated by `scripts/licences.py`
/// from `licences/` (the app's own) and core's notices (the web map's).
struct Licence: Decodable {
    /// What it is, in English; looked up in the translations first.
    let name: String
    /// Its licences, such as `MIT` or `BSD-3-Clause`.
    let licence: String
    /// The copyright lines and licence texts, verbatim.
    let text: String

    static let all: [Licence] = {
        guard let url = Bundle.main.url(forResource: "Licences", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let licences = try? JSONDecoder().decode([Licence].self, from: data) else {
            assertionFailure("Licences.json missing or malformed")
            return []
        }
        return licences
    }()
}

/// The open-source licences, linked from the bottom of Settings. A tap
/// shows one in full.
final class LicencesViewController: UITableViewController {
    init() {
        super.init(style: .insetGrouped)
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) is not supported")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        title = NSLocalizedString("open_source_header", comment: "licence")
        navigationItem.rightBarButtonItem = UIBarButtonItem(systemItem: .done, primaryAction: UIAction { [weak self] _ in
            self?.dismiss(animated: true)
        })
        tableView.register(UITableViewCell.self, forCellReuseIdentifier: "licence")
        tableView.accessibilityIdentifier = "licences"
    }

    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        Licence.all.count
    }

    override func tableView(_ tableView: UITableView, titleForFooterInSection section: Int) -> String? {
        NSLocalizedString("open_source_footer", comment: "licence")
    }

    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "licence", for: indexPath)
        let licence = Licence.all[indexPath.row]
        var content = UIListContentConfiguration.subtitleCell()
        content.text = NSLocalizedString(licence.name, comment: "licence")
        content.secondaryText = licence.licence
        content.secondaryTextProperties.color = .secondaryLabel
        cell.contentConfiguration = content
        cell.accessoryType = .disclosureIndicator
        return cell
    }

    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        navigationController?.pushViewController(LicenceViewController(licence: Licence.all[indexPath.row]), animated: true)
    }
}

/// Shows one `Licence` in full, selectable so it can be copied.
final class LicenceViewController: UIViewController {
    private let licence: Licence

    init(licence: Licence) {
        self.licence = licence
        super.init(nibName: nil, bundle: nil)
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) is not supported")
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        title = NSLocalizedString(licence.name, comment: "licence")
        view.backgroundColor = .systemBackground
        let text = UITextView()
        text.isEditable = false
        text.text = licence.text
        // Licence texts are laid out for a fixed-width font: lists, indents.
        text.font = UIFontMetrics(forTextStyle: .footnote).scaledFont(for: .monospacedSystemFont(ofSize: 12, weight: .regular))
        text.adjustsFontForContentSizeCategory = true
        text.textColor = .label
        text.textContainerInset = UIEdgeInsets(top: 16, left: 12, bottom: 16, right: 12)
        text.accessibilityIdentifier = "licence.text"
        text.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(text)
        NSLayoutConstraint.activate([
            text.topAnchor.constraint(equalTo: view.topAnchor),
            text.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            text.leadingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.leadingAnchor),
            text.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor),
        ])
    }
}
