#!/usr/bin/env python3
"""Generate meteocool/AR/Colormaps.swift from meteocool/core's palettes.

The AR storm view paints reflectivity in the palette the reader picked for the
radar map ("Radar Color Map" in Settings), so a 45 dBZ core is the same yellow
over the sky as on the map. The tables live in core (`src/colormaps.ts`) and
are copied here by this script rather than by hand: six tables of a few
hundred RGBA entries each are not something to retype.

Usage:
    python3 scripts/colormaps.py [path/to/core]

The core checkout defaults to $MC_CORE, then ../core next to this repository.
Rerun it whenever core's palettes change and commit the output.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "meteocool" / "AR" / "Colormaps.swift"

# Core's names, as the `radarColorMapping` setting stores them, and the
# TypeScript constants that hold each table.
PALETTES = {
    "classic": "RVP6_CLASSIC",
    "nws": "RVP6_NWS",
    "viridis": "RVP6_VIRIDIS",
    "pyart_stepseq": "RVP6_PYART_STEPSEQ",
    "homeyer": "RVP6_HOMEYER",
    "lang": "RVP6_LANG",
}


def core_path() -> Path:
    if len(sys.argv) > 1:
        return Path(sys.argv[1])
    if os.environ.get("MC_CORE"):
        return Path(os.environ["MC_CORE"])
    return ROOT.parent / "core"


def table(source: str, name: str) -> list[tuple[int, int, int, int]]:
    match = re.search(rf"export const {name}: Rgba\[\] = \[(.*?)\];", source, re.S)
    if not match:
        sys.exit(f"{name} not found in colormaps.ts")
    entries = re.findall(r"\[(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\]", match.group(1))
    return [tuple(int(v) for v in entry) for entry in entries]  # type: ignore[misc]


def pad(source: str, name: str) -> int:
    match = re.search(rf"export const {name}_LEFTPAD = (\d+);", source)
    if not match:
        sys.exit(f"{name}_LEFTPAD not found in colormaps.ts")
    return int(match.group(1))


def main() -> None:
    path = core_path() / "src" / "colormaps.ts"
    if not path.exists():
        sys.exit(f"{path} does not exist; pass the core checkout as the first argument")
    source = path.read_text()

    lines = [
        "// Generated by scripts/colormaps.py from meteocool/core src/colormaps.ts.",
        "// Do not edit; rerun the script instead.",
        "",
        "/// The radar map's palettes, as `(leftPad, [r, g, b, a])` per setting value.",
        "///",
        "/// Index `i` of the full scale is `(dBZ + 32.5) * 2`, in half-decibel steps;",
        "/// the table starts at `leftPad`, and everything below it is transparent.",
        "/// See `Colormaps.colour(dbz:palette:)`.",
        "enum ColormapTables {",
        "    static let tables: [String: (leftPad: Int, rgba: [UInt32])] = [",
    ]
    for key, constant in PALETTES.items():
        entries = table(source, constant)
        packed = [f"0x{r:02X}{g:02X}{b:02X}{a:02X}" for r, g, b, a in entries]
        rows = [", ".join(packed[i : i + 8]) for i in range(0, len(packed), 8)]
        lines.append(f'        "{key}": ({pad(source, constant)}, [')
        lines.extend(f"            {row}," for row in rows)
        lines.append("        ]),")
    lines += ["    ]", "}", ""]
    OUTPUT.write_text("\n".join(lines))
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
